import Layout from '../components/Layout'
import { ContentsNav, Section, Invitation, NextReads, Footnotes, ArticleFooter, ArticleWrap } from '../components/Article'

const SECTIONS = []

export default function EnvCarbonMarketsAreEnclosures() {
  return (
    <Layout
      title="Carbon Markets Are the New Enclosures — Power Explained"
      description="REDD+, nature-based solutions, biodiversity credits — the financialization of the atmosphere and the living world is being sold as climate action. It is, structurally, the same mechanism that caused the problem: enclosure dressed in green."
      seriesTag="For Environmentalists"
    >
      <div className="hero" style={{ background: 'var(--ink)', color: 'var(--paper)', padding: 'clamp(3rem,8vw,6rem) var(--gutter) clamp(2.5rem,6vw,4.5rem)', position: 'relative', overflow: 'hidden' }}>
        
        <div className="hero-inner" style={{ maxWidth: 'var(--max)', margin: '0 auto', position: 'relative' }}>
          
          <h1 dangerouslySetInnerHTML={{ __html: `Carbon Markets<br />Are the<br />New Enclosures` }} />
          <p className="hero-dek">REDD+, nature-based solutions, biodiversity credits — the financialization of the atmosphere and the living world is being sold as climate action. It is, structurally, the same mechanism that caused the problem.</p>
          
        </div>
      </div>

      <ArticleWrap>
        
        <div className="body-text">
          
          <div dangerouslySetInnerHTML={{ __html: `<div class="nav-strip">
<a href="for-environmentalists.html">Overview</a>
<a href="env-enclosure-and-extinction.html">I. Enclosure &amp; extinction</a>
<a href="env-indigenous-land-governance.html">II. Indigenous governance</a>
<a class="current" href="env-carbon-markets-are-enclosures.html">III. Carbon markets</a>
</div>
<p>The logic of carbon markets goes like this: emitting carbon has a cost, but no one is currently paying it. So create a price for carbon, let markets allocate reductions to wherever they're cheapest, and emissions fall efficiently. It sounds clean. It has the aesthetic of pragmatism — working with markets rather than against them, not waiting for political consensus on hard limits.</p>
<p>The problem is not the logic. The problem is what happens when you try to build a property right over the atmosphere and the living systems that regulate it. You get enclosure: the conversion of shared commons — the carbon cycle, standing forests, the living systems Indigenous communities govern — into tradeable assets controlled by whoever structures the deal first.</p>
<h2>How REDD+ became a land grab</h2>
<p>REDD+ (Reducing Emissions from Deforestation and Forest Degradation) was designed to pay for keeping forests standing. The mechanism: governments and companies in the Global North pay for "carbon credits" generated by forests in the Global South that aren't being cut down. On paper, everyone wins — emitters offset their pollution, forest nations get revenue, forests stay standing.</p>
<p>In practice, REDD+ projects have repeatedly dispossessed the communities most responsible for forest protection. The credits require defined territories with tradeable carbon rights. But in many cases, the communities actually governing the forests don't hold legal title that a carbon market can recognize — their governance is <a class="xlg" href="env-indigenous-land-governance.html">customary rather than formal</a>. So the credits go to whoever does hold recognizable title: national governments, regional authorities, or NGOs that structured the deal. The communities keep the obligation to protect the forest; the value of the carbon flows elsewhere.</p>
<div class="critique-block">
<span class="critique-label">What the research shows</span>
<h3>The Guardian's REDD+ investigation (2023)</h3>
<p>A year-long <a class="xl" href="https://www.theguardian.com/environment/2023/jan/18/revealed-forest-carbon-offsets-biggest-provider-worthless-verra-aoe" rel="noopener" target="_blank">investigation by The Guardian, Die Zeit, and SourceMaterial</a> examined carbon credits generated by <a class="xl" href="https://verra.org" rel="noopener" target="_blank">Verra</a> — the largest certifier of voluntary carbon offsets. More than 90 percent of their rainforest offset credits were found to be "phantom credits" that didn't represent real carbon reductions. The forest areas generating the credits weren't at significant risk of deforestation in the first place, meaning the credits were selling the non-destruction of forests that weren't going to be destroyed anyway.</p>
<p>This is not a technical accounting error. It's the predictable outcome of a market structure where the incentive is to generate certifiable credits, not to produce actual carbon reductions. <a class="xlr" href="the-alibi-was-a-mirror.html">The alibi was the point</a> — giving fossil fuel companies a mechanism to continue operating at current levels while claiming climate action.</p>
</div>
<h2>The deeper problem: commodifying the commons</h2>
<p>Even a well-functioning carbon market has a structural problem that no amount of improved accounting can fix: it converts a global commons — the atmosphere's capacity to absorb carbon — into a system of privately held property rights. The atmosphere's carbon-processing capacity doesn't belong to anyone. It's the collective inheritance of every living thing on Earth. When you assign that capacity as tradeable credits, you're doing <a class="xl" href="glossary.html#enclosure">enclosure</a> of a commons that no one had the authority to enclose.</p>
<p>The same logic applies to "biodiversity credits" and "natural capital accounting." These frameworks turn the living world into an asset class — quantifying ecosystem services, assigning them property rights, and creating markets where companies can buy the right to damage one ecosystem by protecting another. This isn't conservation. It's the extension of enclosure to the remaining commons.</p>
<div class="pull">
        You can't solve an enclosure crisis<br/>by <strong>enclosing what's left.</strong>
</div>
<h2>The contrast: what actually works</h2>
<div class="contrast">
<div class="contrast-col bad">
<span class="contrast-col-label">Carbon market approach</span>
<h3>Commodify the forest</h3>
<p>Assign carbon rights to forest area. Sell those rights to emitters as offsets. Allow companies to maintain current emission levels in exchange for payment. Generate certifiable credits that represent abstractly "equivalent" carbon reductions elsewhere.</p>
<p>Leaves the governance of the forest as a secondary concern — what matters is the accounting, not the institution that maintains it. Systematically undervalues the community governance that's actually doing the work of protection.</p>
</div>
<div class="contrast-col">
<span class="contrast-col-label">Commons governance approach</span>
<h3>Strengthen the institution</h3>
<p>Recognize and legally secure Indigenous territorial rights. Fund community-based monitoring and enforcement. Transfer real governance authority — not advisory roles — to the communities that have demonstrated they can maintain the ecosystems. Direct finance to those communities, not to intermediaries who hold the tradeable instruments.</p>
<p>Targets the actual mechanism producing protection outcomes: the <a class="xlg" href="env-indigenous-land-governance.html">governance institution</a> with long-term stakes in the ecosystem's survival.</p>
</div>
</div>
<h2>What the environmental movement needs to decide</h2>
<p>Carbon markets have become the dominant framing for climate finance because they're politically easier than alternatives: they don't require capping emissions directly, don't require confronting fossil fuel companies politically, and generate revenue flows that environmental organizations can participate in and benefit from. They're also endorsed by the same financial sector that has spent decades funding the fossil fuel industry — which should be a signal, not a reassurance.</p>
<p>The alternative framing isn't "do nothing." It's direct investment in the governance institutions that produce ecological outcomes: Indigenous territorial rights, community land ownership, <a class="xl" href="build-it-now.html">cooperative resource management</a>, and hard limits on extraction rather than tradeable rights to continue it. This requires confronting the political economy of fossil fuel extraction rather than routing around it.</p>
<p>It also requires the environmental movement to <a class="xlr" href="for-social-justice.html">take seriously its relationship with social justice movements</a> — because the communities on the front lines of both ecological protection and carbon market displacement are the same communities that <a class="xlr" href="racial-capitalism.html">racial capitalism</a> has put there. Climate justice is not a subset of climate action. It's the precondition for it.</p>
<div class="close-box">
<span class="close-label">Series conclusion</span>
<h3>The commons is the climate solution.</h3>
<p>Enclosure caused the ecological crisis. More enclosure — of the atmosphere, of the genetic commons, of the forests that Indigenous communities govern — is not the solution. The most effective climate and biodiversity interventions available are also the most redistributive: secure territorial rights, real governance authority, and direct finance to the communities already doing the work of maintaining living systems.</p>
<p>That's not a romantic vision. It's what the evidence shows. The question is whether the environmental movement is willing to fight for it — which means fighting against the financial structures that offer an easier path to continued extraction dressed in green.</p>
<div class="close-links">
<a class="close-link" href="for-environmentalists.html">Back to overview →</a>
<a class="close-link" href="the-commons-they-never-stopped-building.html">What's being built →</a>
<a class="close-link" href="build-it-now.html">Build it now →</a>
</div>
</div>
<div class="nav-strip">
<a href="env-indigenous-land-governance.html">← Indigenous governance</a>
<a href="for-environmentalists.html">Back to overview →</a>
</div>` }} />
        </div>
        
        
        
        <ArticleFooter seriesNote="" />
      </ArticleWrap>
    </Layout>
  )
}
