import Layout from '../components/Layout'
import { ContentsNav, Section, Invitation, NextReads, Footnotes, ArticleFooter, ArticleWrap } from '../components/Article'

const SECTIONS = []

export default function ForTechWorkers() {
  return (
    <Layout
      title="For People Who Build the Internet — Power Explained"
      description="You already understand open source: shared resources, governed by contributors, producing value nobody owns. That's the argument. Applied to housing, healthcare, cities, and everything else."
      seriesTag=""
    >
      <div className="hero" style={{ background: 'var(--ink)', color: 'var(--paper)', padding: 'clamp(3rem,8vw,6rem) var(--gutter) clamp(2.5rem,6vw,4.5rem)', position: 'relative', overflow: 'hidden' }}>
        <div style={{ position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%,-50%)', fontFamily: 'var(--display)', fontSize: 'clamp(4rem,18vw,12rem)', fontWeight: 700, letterSpacing: '-0.04em', opacity: 0.05, whiteSpace: 'nowrap', pointerEvents: 'none', lineHeight: 1 }}>OPEN</div>
        <div className="hero-inner" style={{ maxWidth: 'var(--max)', margin: '0 auto', position: 'relative' }}>
          <span className="hero-eyebrow">Entry Point — Tech Workers — Open Source as Political Theory</span>
          <h1 dangerouslySetInnerHTML={{ __html: `You Already<br />Understand <em>This</em>` }} />
          <p className="hero-dek">Open source: shared resources, governed by contributors, producing value that no single actor owns. Linux runs the internet. Wikipedia has outcompeted every encyclopedia ever funded. The argument works. You already know it. This is what it looks like applied to everything else.</p>
          
        </div>
      </div>

      <ArticleWrap>
        
        <div className="body-text">
          
          <div dangerouslySetInnerHTML={{ __html: `<div class="section-kicker"><span class="section-num">01</span><div class="section-rule"></div></div>
<h2>The thing you built your career on</h2>
<p>Linux was written by thousands of contributors who weren't paid to write it, don't own it, and can't be excluded from using it. It now runs the majority of the world's servers, every Android phone, and the infrastructure of most of the internet economy. The companies that depend on it contributed back, or they didn't, but the kernel kept compiling either way.</p>
<p>This is a governance success story. A shared resource, maintained collectively, producing value at a scale no private actor could have funded or controlled. The "tragedy of the commons" — <a class="xl" href="hardin-was-wrong.html">which was never an accurate description of actual commons governance anyway</a> — does not describe Linux. It doesn't describe Wikipedia, or the TCP/IP stack, or HTTPS, or the programming languages most of your codebase runs on.</p>
<p>The open source model works because it solves a genuine governance problem: how do you maintain a shared resource when contributors have heterogeneous incentives, no one owns the output, and the cost of defection is low? The answer, it turns out, is not private property or state control. It's <a class="xl" href="ostrom.html">a specific set of institutional arrangements</a> — clear contribution rules, transparent governance, mechanisms for resolving disputes, and norms that make free-riding costly enough that most contributors don't.</p>
<p><a class="xl" href="how-linux-became-the-internet.html">This site has a piece on exactly that.</a> But the argument extends further than software.</p>
<div class="section-kicker"><span class="section-num">02</span><div class="section-rule"></div></div>
<h2>The enclosure of the commons you built</h2>
<p>Here's the pattern you've watched happen in real time: a commons gets built — open protocols, shared infrastructure, network effects generated by millions of users — and then a platform encloses it. Extracts value from it. Routes everything through a proprietary layer that charges rent for access to what was built collectively.</p>
<p>Twitter's API was open. Developers built a whole ecosystem on it. Then the API got paywalled, the ecosystem got destroyed, and the platform extracted the value those developers had created. Facebook's news feed was a commons of attention and social connection; it got enclosed into an advertising auction. App stores take 30% of revenue from developers building on shared infrastructure the developers' own customers purchased.</p>
<div class="versus">
<div class="versus-side dim">
<span class="versus-label">The commons phase</span>
<div class="versus-claim">Open API. Developer ecosystem. Network effects built by users. Platform grows on shared contribution.</div>
<div class="versus-note">Value created collectively. Access open. Rules stable enough to build on.</div>
</div>
<div class="versus-side">
<span class="versus-label red">The enclosure phase</span>
<div class="versus-claim">API paywalled. Terms changed. Value extracted. Developers locked out or charged rent to access what they built.</div>
<div class="versus-note">This is not a bug or a betrayal. It's the business model. <a class="xl" href="glossary.html#capture">Capture</a> was always the plan.</div>
</div>
</div>
<p>This is <a class="xl" href="glossary.html#primitive-accumulation">primitive accumulation</a> in digital form — the process by which a commons gets converted into private property. It happened to common land in England across three centuries. It's happening to digital infrastructure in real time, and you have a front-row seat.</p>
<p><a class="xl" href="open-data-isnt-enough.html">Open data is not enough.</a> Transparency without governance is just a better-looking black box. What makes a commons a commons is not that you can see it — it's that the people who depend on it have meaningful say in how it's run.</p>
<div class="section-kicker"><span class="section-num">03</span><div class="section-rule"></div></div>
<h2>The AI enclosure is happening right now</h2>
<p>The large language models were trained on the commons: the accumulated written output of millions of people across decades of public internet. Stack Overflow answers, Wikipedia articles, GitHub repositories, forum posts, blog entries, academic papers. None of those contributors were compensated. None of them consented to their work being used as training data. The value of the commons — the accumulated knowledge infrastructure of the internet — was ingested and converted into proprietary weights.</p>
<p>This is not a legal argument. It may or may not be copyright infringement in any particular jurisdiction. It is a commons argument: a shared resource was treated as free input for private extraction, and the people who built the resource have no governance over the output.</p>
<p>The federated web — ActivityPub, AT Protocol, the network of Mastodon instances and other decentralized platforms — is a live experiment in the alternative. Not perfect. Not yet at scale for most uses. But architecturally committed to the principle that the governance of the infrastructure should belong to the people who depend on it, not to a platform with different incentives.</p>
<div class="section-kicker"><span class="section-num">04</span><div class="section-rule"></div></div>
<h2>The same argument, applied to everything</h2>
<p>Housing works the same way. A neighborhood's value — its walkability, its social fabric, its accumulated character — is produced collectively by everyone who lives there. A landlord who owns property in that neighborhood captures rent from that collectively produced value without having contributed to it. When the neighborhood becomes desirable enough, the landlord can extract enough rent to displace the people who made it desirable. The commons gets enclosed. <a class="xl" href="why-your-city-doesnt-work.html">This is why your city doesn't work.</a></p>
<p>Healthcare works the same way. Medical knowledge is built collectively — through publicly funded research, clinical training in public hospitals, accumulated practice shared across a profession — and then enclosed behind insurance systems, pharmaceutical patents, and billing architectures that extract rent from the commons of medical knowledge.</p>
<p>The pattern is consistent: a community builds something shared, an extraction system routes value from that shared thing through private ownership before it reaches the people who built it, and a story gets told that makes the arrangement seem natural or inevitable. <a class="xl" href="gramsci.html">That story is hegemony.</a> The arrangement it justifies is capture. And there's always an alternative — which is why the story has to keep being told.</p>
<div class="pull">
        Open source is not a software philosophy.<br/>It's a <strong>theory of governance</strong><br/>that turns out to be correct.
      </div>
<div class="section-kicker"><span class="section-num">05</span><div class="section-rule"></div></div>
<h2>What's being built</h2>
<p>Platform cooperatives are worker-owned digital platforms that apply the cooperative model to gig work. Driver-owned rideshare cooperatives, cleaner-owned domestic work platforms, journalist-owned media outlets. They're smaller than Uber or DoorDash. They're also not designed to extract value from their workers and route it to investors. The trade-off is explicit.</p>
<p>Community land trusts remove housing from the speculative market permanently — the land is owned by a trust, the housing on it is affordable by legal obligation, and residents have governance over the trust. There are over 250 in the United States right now. They work. <a class="xl" href="build-it-now.html">The evidence is public.</a></p>
<p>The federated social web is live and growing. Mastodon, Pixelfed, PeerTube, Bluesky's AT Protocol — architecturally decentralized platforms where no single actor can enclose the network. Not perfect governance. But governance that belongs to the participants rather than to a platform with advertising revenue to maximize.</p>
<div class="callout">
<span class="callout-label">The governance question is always the same</span>
<p>For any shared resource — a software project, a neighborhood, a healthcare system, a social network, a fishery — the question is: who sets the rules, who enforces them, who benefits from what the resource produces, and what happens when the rules need to change?</p>
<p>Private ownership answers: whoever holds the property rights. State control answers: whoever runs the regulatory apparatus. Commons governance answers: the people who depend on and contribute to the resource.</p>
<p>You already know the third answer produces better software. The argument is that it produces better cities, better healthcare systems, and better social infrastructure for the same reasons it produces better kernels.</p>
</div>` }} />
        </div>
        
        
        
        <ArticleFooter seriesNote="" />
      </ArticleWrap>
    </Layout>
  )
}
