#!/usr/bin/env node
/**
 * atlas-xray — the editorial X-ray of the gesture field.
 *
 * The atlas (/book/atlas) shows the rhizome. This script measures it, and in
 * doing so answers the thread-swarm question: "what does the weave tell us
 * about the book?" Everything here is computed from data that already exists —
 * the canonical river manifests, the gesture tags Jason already assigned, and
 * the existing thread manifests. It invents nothing and asserts no new
 * connection; it reports structure.
 *
 * It reports:
 *   - thread coverage of the river (how much of the atlas is still white space)
 *   - ORPHANS: river gestures on zero threads (candidates for "disconnected")
 *   - SUPER-NODES: gestures on the most threads (the load-bearing spine)
 *   - the most common significant tags among river gestures, with how many of
 *     each are still unthreaded — i.e. the strongest UNREALIZED thread spines,
 *     grounded in Jason's own tags (the connection is already his)
 *   - per-chapter thread density
 *
 * Writes analysis/atlas-xray.md and prints a summary.
 * Run: node scripts/atlas-xray.mjs
 */
import fs from "node:fs";
import path from "node:path";
import url from "node:url";
import { loadCorpus } from "../src/lib/load-corpus.mjs";
import { loadThreads } from "../src/lib/threads.mjs";
import yaml from "js-yaml";

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

const SIGNIFICANT = ["image/", "place/", "person/", "motif/", "concept/", "school/"];
const DENY = new Set(["concept/commons", "concept/community", "concept/practice"]);

function isSignificant(t) {
  return SIGNIFICANT.some((p) => t.startsWith(p)) && !DENY.has(t);
}

// --- the river gesture set (canonical order, chapter by chapter) ----------
const corpus = loadCorpus(ROOT);
const riverPath = path.join(ROOT, "src", "content", "manifests", "the-river.manifest.yml");
const river = yaml.load(fs.readFileSync(riverPath, "utf8")) || {};
const sources = river.sources || river.chapters || [];
const bySlug = Object.fromEntries(corpus.plateaus.map((p) => [p.slug, p]));

const chapters = sources
  .map((slug) => bySlug[slug])
  .filter(Boolean)
  .map((p) => ({ slug: p.slug, title: p.title || p.slug, ids: p.gestures || [] }));

const riverIds = new Set(chapters.flatMap((c) => c.ids));

// --- thread membership ----------------------------------------------------
const threads = loadThreads();
const onThreads = {}; // id -> [threadH1]
for (const t of threads) {
  for (const id of t.gestures) (onThreads[id] ||= []).push(t.h1 || t.title || t.slug);
}

const tagsOf = (id) => corpus.gestures[id]?.tags || [];

// --- coverage -------------------------------------------------------------
const riverArr = [...riverIds];
const threaded = riverArr.filter((id) => (onThreads[id] || []).length > 0);
const orphans = riverArr.filter((id) => (onThreads[id] || []).length === 0);

// --- super-nodes ----------------------------------------------------------
const superNodes = riverArr
  .map((id) => ({ id, n: (onThreads[id] || []).length, threads: onThreads[id] || [] }))
  .filter((x) => x.n >= 2)
  .sort((a, b) => b.n - a.n)
  .slice(0, 20);

// --- tag frequency among river gestures, with unthreaded counts -----------
const tagCount = new Map(); // tag -> { total, unthreaded }
for (const id of riverArr) {
  const unthreaded = (onThreads[id] || []).length === 0;
  for (const t of tagsOf(id)) {
    if (!isSignificant(t)) continue;
    const e = tagCount.get(t) || { total: 0, unthreaded: 0 };
    e.total += 1;
    if (unthreaded) e.unthreaded += 1;
    tagCount.set(t, e);
  }
}
const topTags = [...tagCount.entries()]
  .map(([tag, e]) => ({ tag, ...e }))
  .filter((e) => e.total >= 3)
  .sort((a, b) => b.total - a.total);

// --- per-chapter density --------------------------------------------------
const perChapter = chapters.map((c) => {
  const n = c.ids.length;
  const on = c.ids.filter((id) => (onThreads[id] || []).length > 0).length;
  return { slug: c.slug, title: c.title, n, on, pct: n ? Math.round((100 * on) / n) : 0 };
});

// --- render ---------------------------------------------------------------
const pct = riverArr.length ? ((100 * threaded.length) / riverArr.length).toFixed(1) : "0";
const titleOf = (id) => corpus.gestures[id]?.title || id;

const lines = [];
lines.push("# Atlas X-ray — what the weave tells us\n");
lines.push("> Generated by `node scripts/atlas-xray.mjs`. All figures computed from the");
lines.push("> canonical river manifests, the existing gesture tags, and the thread");
lines.push("> manifests. No new prose, no asserted connections — structure only.\n");

lines.push("## Coverage\n");
lines.push(`- River gestures: **${riverArr.length}**`);
lines.push(`- On at least one thread: **${threaded.length}** (${pct}%)`);
lines.push(`- Orphans (on zero threads): **${orphans.length}**`);
lines.push(`- Threads: **${threads.length}**`);
lines.push(`- Multi-thread nodes (on ≥2): **${superNodes.length >= 20 ? "20+" : superNodes.length}**\n`);

lines.push("## The load-bearing spine (super-nodes)\n");
lines.push("Gestures where the most threads already cross — the book's structural pivots.\n");
for (const s of superNodes) {
  lines.push(`- **${s.id}** (${s.n}) — ${titleOf(s.id)} · _${s.threads.join(", ")}_`);
}
lines.push("");

lines.push("## Strongest unrealized thread spines\n");
lines.push("The most common significant tags among river gestures, and how many of");
lines.push("each are still on no thread. High `unthreaded` = a strong candidate thread");
lines.push("whose connection Jason has *already made* (the tag). Top 30:\n");
lines.push("| tag | gestures | unthreaded |");
lines.push("| --- | ---: | ---: |");
for (const e of topTags.slice(0, 30)) {
  lines.push(`| \`${e.tag}\` | ${e.total} | ${e.unthreaded} |`);
}
lines.push("");

lines.push("## Per-chapter thread density\n");
lines.push("| chapter | gestures | threaded | % |");
lines.push("| --- | ---: | ---: | ---: |");
for (const c of perChapter) {
  lines.push(`| ${c.title} | ${c.n} | ${c.on} | ${c.pct}% |`);
}
lines.push("");

const out = path.join(ROOT, "analysis", "atlas-xray.md");
fs.writeFileSync(out, lines.join("\n"));

console.log(`river gestures      ${riverArr.length}`);
console.log(`threaded            ${threaded.length} (${pct}%)`);
console.log(`orphans             ${orphans.length}`);
console.log(`threads             ${threads.length}`);
console.log(`super-nodes (>=2)   ${superNodes.length >= 20 ? "20+" : superNodes.length}`);
console.log(`\ntop unrealized spines (tag · total · unthreaded):`);
for (const e of topTags.slice(0, 12)) {
  console.log(`  ${e.tag.padEnd(28)} ${String(e.total).padStart(3)}   ${String(e.unthreaded).padStart(3)}`);
}
console.log(`\nwrote analysis/atlas-xray.md`);
